<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE food
[
<!ELEMENT food (name,price,description,calories,copy)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT calories (#PCDATA)>
<!ELEMENT copy (#PCDATA)>
<!ENTITY copyright "Copyright: OddlyStudios.">
]>
  <food>
    <name>Belgian Waffles</name>
    <price>$5.95</price>
    <description>Two of our famous Belgian Waffles with plenty of real maple syrup</description>
    <calories>650</calories>
    <copy>&copyright;</copy>
  </food>